### ISSUE TITLE
Cannot change sheet

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#222] opened 2020-09-17 00:55 UTC
**Describe the bug**
In `development` branch error when trying to change sheets by clicking on the tab buttons at the bottom of the data file pane.

![image](https://user-images.githubusercontent.com/1087657/93406498-a4870c80-f844-11ea-8e1a-b86241ea5894.png)

**To Reproduce**
1. Open a project, say https://github.com/usc-isi-i2/t2wml/blob/development/tutorial/Region_Tutorial/project.t2wml
2. Then, open another project `File -> Open Project`, say https://github.com/usc-isi-i2/t2wml/blob/development/tutorial/Time_Qualifier_Tutorial/project.t2wml
3. Click on a tab button

**Comment by devowit** [comment] 2020-09-17 13:26
successfully replicated, and the cause is the same pid synchronization issue that has been haunting us in other issues. clearly did not succeed in eradicating it. side note: reloading the page does not help, we still have the wrong pid stored.

**Comment by kyao** [comment] 2020-09-21 20:25
Tested

**Comment by saggu** [comment] 2020-10-05 17:02
Closing

**Closed by saggu** 2020-10-05 17:02 UTC
Labels: Tested OK, bug
