### ISSUE TITLE
Loading a wikifier file with corrections fails

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#320] opened 2020-12-28 05:24 UTC
I created a project, defined the annotations, loaded a wikifier file, noticed it had an error, edited and loaded again. Strangely, it still shows the incorrect q-node in the outpu: it shows sustainable development goals, which was the previous value. You can see in the wikifier display that the q-node for Colt 45 is Q51... (the value after correction) and the value in the output is Q76...

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/1074599/103191568-5396a380-488a-11eb-9881-f1c04f37c694.png">

There were also several crashes when trying to upload the wikifier file as it had syntax errors so it is possible that the state got corrupted in the process

**Comment by devowit** [comment] 2020-12-28 11:19
two questions:

1. when editing the wikifier, you edited the wikifier file within the project folder, correct? or you re-uploaded a wikifier from outside the project folder?
2. if you re-apply the yaml does the problem go away? (if so the problem is the old results were cached and not updated when you changed the yaml-- I will need to change the caching mechanism to take this into account)

**Comment by szeke** [comment] 2020-12-28 16:55
I edited the file outside and then did upload. I replied the YAML and the problem was still there

**Comment by devowit** [comment] 2021-01-11 08:50
this was a problem caused by the caching mechanism, which did not recognize the same name wikifier file as a reason to redo the calculation instead of returning cached results.

I have disabled caching for now. it is useful for performance, but we need to think about how we want it to work in terms of recognizing changes, and I figure we can do that later, when also doing a general sweep for performance improvements.

**Comment by devowit** [comment] 2021-01-18 15:24
should be fixed in 2.6.1

**Closed** 2021-03-17 08:36 UTC
Labels: bug
