### ISSUE TITLE
Wrong annotation color

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#593] opened 2021-08-09 19:00 UTC
Column D is annotated as property. It should be displayed as yellow. But, it is displayed as purple.

While I was trying to annotate column, the popup window closed due to issue #589. Perhaps that caused column D to be annotated twice?

![Screenshot from 2021-08-09 11-46-41](https://user-images.githubusercontent.com/1087657/128758457-76bb6494-0803-4ee4-bed9-b6486ccc7fc0.png)

Here is project file:
[IDP_partial_1628534669193.zip](https://github.com/usc-isi-i2/t2wml/files/6956726/IDP_partial_1628534669193.zip)

**Comment by g1eb** [comment] 2021-08-09 20:25
I think this could be related to this other issue here [https://github.com/usc-isi-i2/t2wml/issues/590](https://github.com/usc-isi-i2/t2wml/issues/590)

Either way I'm investigating and will let you know in a bit

**Comment by g1eb** [comment] 2021-08-12 18:27
@kyao I'm not sure how this is possible, the data returned from uploading the `.t2wmlz` file you shared has 2 annotation blocks with the same selection but one of them is a property and the other is a qualifier. See screenshot below:

![Screen Shot 2021-08-12 at 11 25 52 AM](https://user-images.githubusercontent.com/1916056/129249382-2eebc6b1-9d78-48bf-8dd7-63f58ddfae1f.png)

Do you have the original/source `.csv` file we can try uploading to see if we can reproduce this issue?

**Comment by kyao** [comment] 2021-08-12 20:03
Here is the original csv file:

[IDP_partial.zip](https://github.com/usc-isi-i2/t2wml/files/6978270/IDP_partial.zip)

**Comment by g1eb** [comment] 2021-08-12 20:49
Thanks for sharing the original CSV file. I'm not able to reproduce this on [https://t2wml.isi.edu/](https://t2wml.isi.edu/)

If this is GUI related then it might be already fixed. What steps did you take in order to reproduce this? 

I think either way we should not allow users to create annotation blocks with the same selection twice, we can add backend validation for this with appropriate errors shown in the GUI. Let me know what you think of this solution.

**Comment by kyao** [comment] 2021-08-12 21:30
I also am not able to reproduce on t2wml.isi.edu.

I uploaded the IDP partial csv file. Applied suggest annotations. Selected column D2:D11. In the popup window I changed range to D2:D1049. Then, as I tried to change the role from qualifier to property, the popup window just disappeared.  Column D is displayed as purple with qualifier role. Then I clicked on D and changed it to property role. This time Column D is yellow with property role.

Not allowing users to create annotation blocks with the same selection twice sound good. We do not have any datasets that would require multiple annotations.

**Comment by g1eb** [comment] 2021-08-12 21:38
Okay, your description of the reproduction steps is the same as what I've tried, I'll close this until we run into it again.

And I'll create a separate ticket for backend validation of multiple annotation blocks with the exact same selection area, see [https://github.com/usc-isi-i2/t2wml/issues/602](https://github.com/usc-isi-i2/t2wml/issues/602)

**Closed by g1eb** 2021-08-12 21:38 UTC
Labels: bug
