### ISSUE TITLE
app crashes, cannot set property classnames of undefined

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#354] opened 2021-02-07 07:52 UTC
steps to reproduce:

open a sheet
make an annotation block (encompassing cells from empty columns). set role to metadata
press submit

app crashes with error as above

**Comment by g1eb** [comment] 2021-02-08 04:45
which branch is this happening on?

**Comment by g1eb** [comment] 2021-02-08 04:52
can not reproduce on the `development` branch, please reopen if this is still happening elsewhere

**Comment by g1eb** [comment] 2021-02-08 07:14
This seems to be happening when one is selecting cells truly outside the range of any original data.

```
Uncaught (in promise) TypeError: Cannot set property 'classNames' of undefined
    at AnnotationTable.updateAnnotationBlocks (annotation-table.tsx:201)
    at AnnotationTable.<anonymous> (annotation-table.tsx:801)
    at callCallback (react-dom.development.js:12490)
    at commitUpdateQueue (react-dom.development.js:12511)
    at commitLifeCycles (react-dom.development.js:19858)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
```

**Comment by g1eb** [comment] 2021-02-08 09:58
fixed in the `development` branch now

**Closed by g1eb** 2021-02-08 09:58 UTC
Labels: bug
