### ISSUE TITLE
Delete project by moving it to trash or the recycle bin

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/t2wml#228] opened 2020-09-17 15:11 UTC
We couldn't get file deletion to work properly on the electron side (not by sending to trash, and not by deleting the folder - I think it's a matter of something thinking there's a file open, even though there isn't). The Python side can delete files properly, so let's make it move files to the Trash or Recycle Bin.

https://pypi.org/project/Send2Trash/ should be able to handle that easily.

**Comment by devowit** [comment] 2020-09-22 07:19
duplicate of @232

**Closed by devowit** 2020-09-22 07:19 UTC
