### ISSUE TITLE
enable skip_cells-like functionality for qualifiers as well

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#158] opened 2020-08-12 14:32 UTC

**Comment by saggu** [comment] 2020-08-12 14:34
This might be a duplicate of #149

**Comment by devowit** [comment] 2020-08-12 14:42
it's not, but looking at that issue was what reminded me to add this one.
this one is adding a syntax feature, that one is modifying the kgtk generation code.

**Comment by devowit** [comment] 2020-11-15 13:04
overlaps with #279

**Comment by devowit** [comment] 2020-11-25 11:28
with #279 added, skip_cells is supported. close when tested in version 2.4.0

**Closed** 2021-02-04 07:24 UTC
Labels: enhancement
