### ISSUE TITLE
Incorrect behavior on the OECD project on version a20

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#121] opened 2020-07-21 05:42 UTC
I see the following problems:

- The wikifier window is not showing any data
- Column B contains wikified properties, but there is no blue highlighting, and clicking on cells in column B produces incorrect behavior as it show data in the output panel as if it was a data cell
- All data cells are colored orange because, for example, `error in cell K106: {'qualifier': {'3': {'property': 'Property not found:P2006020004'}}}`. However, the loaded properties file contains a definition of P2006020004

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1074599/88016937-6afe8300-cad9-11ea-9d93-ad7f595d1b19.png">

[oecd-bug.zip](https://github.com/usc-isi-i2/t2wml/files/4951522/oecd-bug.zip)

**Comment by devowit** [comment] 2020-07-22 03:36
wikifier bug fixed in commit 73f23799

**Comment by devowit** [comment] 2020-07-22 03:38
orange bug: couldn't reproduce in latest commit, but probably because it was fixed in ad199bdf

**Closed** 2020-07-22 03:43 UTC
Labels: bug
