### ISSUE TITLE
Cannot load any tutorial with custom properties in v2.3.7

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#247] opened 2020-09-28 22:12 UTC
**Describe the bug**
I have tried the region and time qualifier tutorial projects (available in the main T2WML repo) and none of them work: 
![image](https://user-images.githubusercontent.com/1520666/94491249-ba79c300-019c-11eb-90d3-256f2a5b661d.png)
As you can see in the image, the PProduction is correctly declared in the wikifier. I checked the type and it's "Quantity"

I tried: 
- Reloading the project.
- Reloading the app.
- Refreshing the project  (F5)
- Reloading the files separately (as a new project); including the tsv file with the properties.
- Uninstalling and installing v2.3.7 of T2WML.

**To Reproduce**
Load any of the project tutorials in the T2WML tutorial folder. Click on apply.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.7

**Comment by devowit** [comment] 2020-09-29 11:15
I have tried to replicate this bug from the repo code with no success. I downloaded the executable and was also not able to replicate. I'm not sure what's going on. Is anyone else having this issue?

**Comment by saggu** [comment] 2020-09-29 17:14
Cannot replicate this as well, version 2.3.7.

@dgarijo does this still happen when you create a new project in an empty folder?

**Comment by dgarijo** [comment] 2020-09-29 17:25
Yes,
I created a new folder, uploaded the files of the project individually (file, wikifier, entities) and still get the error. When I load the properties.tsv it tells me that some properties could not be imported, but I cannot see errors in the console:

![image](https://user-images.githubusercontent.com/1520666/94593141-0cbef080-023e-11eb-8285-4bb0c27c0713.png)

Any ideas? I don't know what I could be doing wrong. Have you tested in Windows?

**Comment by saggu** [comment] 2020-09-29 17:30
I have done the same in Mac version. Same input files, property files etc. @kyao could you give this a test in Windows?

**Comment by dgarijo** [comment] 2020-09-29 17:37
The only thing I haven't done is restart my machine after install. I will give that at try and report back (can't right now)

**Comment by devowit** [comment] 2020-09-29 18:53
is it also happening when you run the code from the repo following the developer instructions?

**Comment by devowit** [comment] 2020-09-29 18:56
also, please expand the failed array in the console screenshot you attached, as that lists properties that failed to upload and the error message for why

![image](https://user-images.githubusercontent.com/22745815/94603149-88508a00-029e-11eb-8330-dc8926fdb2e6.png)

**Comment by dgarijo** [comment] 2020-09-29 19:10
Here is the array expanded:
![image](https://user-images.githubusercontent.com/1520666/94604487-a1304f80-024c-11eb-8ee9-91e6d4a104c5.png)
Interestingly, the properties that fail are updated successfully:
![image](https://user-images.githubusercontent.com/1520666/94604560-bad19700-024c-11eb-9e14-23adb9d302eb.png)

I have not tried the developer code

**Comment by dgarijo** [comment] 2020-10-01 05:56
More news:
* I have installed version 2.3.6 and created a new project. With that version, it works fine.
* If I try to open a project with 2.3.6 I get a "cannot fetch" error, which I guess it was because the open project feature was on test.

This reinforces the thought that 2.3.7 does not work in Windows.

**Comment by dgarijo** [comment] 2020-10-01 18:18
In Windows @kyao? I have gone with @saggu through my steps and he's seen how everything works in 2.3.6 but not in 2.3.7.

**Comment by kyao** [comment] 2020-10-01 18:25
I tried it on Windows.

Which property file failed to load for you? I can try it on my setup.

**Comment by dgarijo** [comment] 2020-10-01 18:28
The wikifier loads PCropType and PProduction successfully (as shown in the first picture). However, T2WML fails to recognize them.

I loaded the tutorials as they are with no changes on my end

**Comment by saggu** [comment] 2020-10-02 00:23
@dgarijo I have got some bad news for you, I tried the same steps on my windows machine and it worked fine.
See below,
![image](https://user-images.githubusercontent.com/6811931/94875707-6e33ba80-040a-11eb-967f-113f45c9f003.png)

However, when I uploaded the properties file, I did not get any error message. (18 added successfully). Maybe there is a clue there somewhere @devowit can shred some light on.

PS: Time to get a new laptop :)

**Comment by dgarijo** [comment] 2020-10-02 01:14
There must be something we are missing. I have not a clue what could it be. 
My laptop is fine :(

**Comment by dgarijo** [comment] 2020-10-02 01:14
Sorry, closed issue accidentally

**Comment by devowit** [comment] 2020-10-02 08:42
@dgarijo  well i have good news which is that we may have replicated the issue on @talyashra's computer, AND we may have found a related issue while working on annotation-integration

**Comment by dgarijo** [comment] 2020-10-02 18:59
Ah, awesome, thanks @devowit !

**Comment by saggu** [comment] 2020-10-03 00:09
@dgarijo @devowit I found the root cause of this problem
It is happening because of the following entry in the `entities.db`
![image](https://user-images.githubusercontent.com/6811931/94978192-1ca23300-04d1-11eb-9099-712d5082dfad.png)

In this case there is no cache id, so backend is throwing an error while looking for `P2006020004`

Here is how to solve this issue,

1. Stop T2WML
2. Delete `entities.db` file in the `.t2wml` folder in your home directory.
3. Start T2WML
4. The issue should be solved now.

@devowit How did this entry get into the database in the first place? Might be worth looking into

**Comment by dgarijo** [comment] 2020-10-03 00:28
I have tested and this does address my problem.
Thanks!!
Feel free to close this issue.

**Comment by saggu** [comment] 2020-10-03 00:45
This is the responsible line in the code:

https://github.com/usc-isi-i2/t2wml/blob/development/backend/wikidata_models.py#L70

In a for loop it checks if cache id is None, so if this entry is above the actual project related entry, it'll throw an error.

Weirdest form of russian roulette :)

**Comment by devowit** [comment] 2020-10-04 09:37
OK, I now understand where the issue is coming from (running a project before entities defined will fill it with caches of Property Not Found, and then because of the project-specific ID this won't be overwritten when uploading a proper definition). Happy Daniel is able to continue working, please don't close the issue until we've fixed the underlying problem.

**Comment by devowit** [comment] 2020-10-15 09:42
this was fixed in  245c4a1b (with some tweaks in subsequent commits) and should be released in the next version (2.3.8)

**Comment by devowit** [comment] 2020-11-11 07:18
@dgarijo @saggu  is the problem fully gone and if so can we close this?

**Comment by dgarijo** [comment] 2020-11-11 17:10
From my end I already said this issue can be closed :)

**Closed** 2020-11-11 17:10 UTC
Labels: bug
