### ISSUE TITLE
Copy/paste does not work in mac executable

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#184] opened 2020-08-21 15:52 UTC
When we were working on the tutorial today, mac users had a problem with the command in mac (it did not work), and they could not copy/paste their yaml files in the T2WML editor.

**Comment by saggu** [comment] 2020-08-25 17:25
@dgarijo this is a duplicate of issue #168 

Closing this one

**Closed by saggu** 2020-08-25 17:25 UTC
Labels: bug, duplicate
