### ISSUE TITLE
auto-generated yaml functionality

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#316] opened 2020-12-11 16:48 UTC
We've been testing the auto-generating YAML functionality based on the annotation blocks and found that:

1. annotating main subject blocks does not trigger the auto-generated YAML file
2. annotating the dependent variable block does triggers the auto-generated YAML file
3. based on the annotation blocks covered we should have more information in the YAML file

This is what the auto generated YAML file looks like with the various blocks annotated:
![Screen Shot 2020-12-11 at 8 39 16 AM](https://user-images.githubusercontent.com/1916056/101930489-109bb700-3b8d-11eb-9aaa-5394821ca89b.png)

And this is after re-annotating the dependent variable block that triggers the YAML file generation:
![Screen Shot 2020-12-11 at 8 40 16 AM](https://user-images.githubusercontent.com/1916056/101930629-40e35580-3b8d-11eb-9cd1-655da90fb89b.png)

You can see that in the second screenshot YAML file does recognize the qualifier annotation (type=time) even though that annotation was already available before.

**Comment by devowit** [comment] 2020-12-13 07:37
in example one the dependent variable wasn't annotated and in example two it was?

qualifiers are aligned along dependent variable, not along main subject. so if MS is there but DV is not, qualifier alignments won't be generated.  but you should be getting an error message if DV or MS are missing... 

if instead you mean that annotating DV and then MS produced different results than annotating MS and then DV, that is weird, definitely a bug, and I'll look into it.

**Comment by devowit** [comment] 2020-12-13 11:35
1 is caused by annotating main subject blocks having been broken in the frontend during changes to the form. you need to click away from main subject (eg to property) and then back for main subject to actually be submitted, instead of "null"). this is probably leftover from when the first entry in the list was the title of the list ("role") and is a bug that should be fixed. 
2 is not a bug
3-- yes, for example we are often missing properties. 
for certain types, if property is missing, we could supply a default property for that type (eg P585 for dates). For others, the discussion we had about needing to add some kind of support for creating properties is relevant.

That said, the example you've screenshotted above worries me because it seems to have more missing properties than it should. could you please attach the project not just the screenshots so I can check if there's a bug in the alignment code? (important note: there was a bug in how annotations were being saved in project, where absolute instead of relative paths were saved. I've fixed the bug, but you'll need to either recreate the project after pulling t2wml-api or just manually delete the non-relative part of the path from the project file... (I can do that if you'd like))

**Comment by szeke** [comment] 2020-12-13 16:46
The example above is correctly annotated and should work. Column F has the main property (for the variable) and H1 has the property for the qualifier. The unit annotation in column I is associated with the variable in column J as there is no other block with quantities that is missing units.

I understand that the algorithm may not be able to handle the blocks incrementally as it is missing information, but in this example, at the end it should have the correct, fully specified YAML

**Comment by g1eb** [comment] 2020-12-13 20:06
Just to clarify, in both examples everything was already annotated and submitted correctly. It was in our experience the re-submitting of the dependent variable that triggered the YAML generation. Adding the project files below:

[untitled folder.zip](https://github.com/usc-isi-i2/t2wml/files/5685339/untitled.folder.zip)

**Comment by devowit** [comment] 2020-12-16 09:02
one part of the problem is that column/row coordinates were being sent in reversed order, ie for one block rows were [1, 19] and in the other block rows were [19,1]

I'll fix this in the backend but @g1eb maybe the frontend shouldn't be sending "flipped" rectangles?

**Comment by devowit** [comment] 2020-12-16 09:05
with that problem fixed, the backend is returning the yamlContent, but for some reason it's not getting displayed in the frontend. it's possible this ties into some of the other yaml bugs we've been having (eg #313), or it might be something entirely separate.

**Comment by devowit** [comment] 2020-12-16 09:20
the yaml wasn't loading because we never actually loaded it in the frontend after getting it from backend. fixed.

**Comment by devowit** [comment] 2020-12-16 09:21
fixed in branch feaature/user-annotations

**Closed** 2021-02-07 06:44 UTC
